# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/sparkles/Games n stuff/CODING/RaylibGuiCreator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/sparkles/Games n stuff/CODING/RaylibGuiCreator"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/sparkles/Games n stuff/CODING/RaylibGuiCreator/CMakeFiles" "/media/sparkles/Games n stuff/CODING/RaylibGuiCreator//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/sparkles/Games n stuff/CODING/RaylibGuiCreator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RaylibGuiCreator

# Build rule for target.
RaylibGuiCreator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RaylibGuiCreator
.PHONY : RaylibGuiCreator

# fast build rule for target.
RaylibGuiCreator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/build
.PHONY : RaylibGuiCreator/fast

Functions.o: Functions.cpp.o
.PHONY : Functions.o

# target to build an object file
Functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/Functions.cpp.o
.PHONY : Functions.cpp.o

Functions.i: Functions.cpp.i
.PHONY : Functions.i

# target to preprocess a source file
Functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/Functions.cpp.i
.PHONY : Functions.cpp.i

Functions.s: Functions.cpp.s
.PHONY : Functions.s

# target to generate assembly for a file
Functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/Functions.cpp.s
.PHONY : Functions.cpp.s

RaylibFunctions.o: RaylibFunctions.cpp.o
.PHONY : RaylibFunctions.o

# target to build an object file
RaylibFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/RaylibFunctions.cpp.o
.PHONY : RaylibFunctions.cpp.o

RaylibFunctions.i: RaylibFunctions.cpp.i
.PHONY : RaylibFunctions.i

# target to preprocess a source file
RaylibFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/RaylibFunctions.cpp.i
.PHONY : RaylibFunctions.cpp.i

RaylibFunctions.s: RaylibFunctions.cpp.s
.PHONY : RaylibFunctions.s

# target to generate assembly for a file
RaylibFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/RaylibFunctions.cpp.s
.PHONY : RaylibFunctions.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/main.cpp.s
.PHONY : main.cpp.s

menus.o: menus.cpp.o
.PHONY : menus.o

# target to build an object file
menus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/menus.cpp.o
.PHONY : menus.cpp.o

menus.i: menus.cpp.i
.PHONY : menus.i

# target to preprocess a source file
menus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/menus.cpp.i
.PHONY : menus.cpp.i

menus.s: menus.cpp.s
.PHONY : menus.s

# target to generate assembly for a file
menus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RaylibGuiCreator.dir/build.make CMakeFiles/RaylibGuiCreator.dir/menus.cpp.s
.PHONY : menus.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RaylibGuiCreator"
	@echo "... Functions.o"
	@echo "... Functions.i"
	@echo "... Functions.s"
	@echo "... RaylibFunctions.o"
	@echo "... RaylibFunctions.i"
	@echo "... RaylibFunctions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... menus.o"
	@echo "... menus.i"
	@echo "... menus.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

